# Makefile for all-dev-jellyfin snap
# Generated by ALL Forge

SNAP_NAME = all-dev-jellyfin
SNAP_FILES = snap/snapcraft.yaml plugin.yaml
SNAPCRAFT ?= snapcraft
SNAPCRAFT_FLAGS ?= --destructive-mode

all: clean validate build

clean:
	@echo "Cleaning"
	@echo "========="
	@rm -rf prime/ stage/ parts/
	@rm -f *.snap
	@echo "[OK] Clean completed"

validate:
	@echo "Validating Project"
	@echo "==================="
	@if [ ! -f snap/snapcraft.yaml ]; then echo "[ERROR] snap/snapcraft.yaml missing"; exit 1; fi
	@if [ ! -f plugin.yaml ]; then echo "[ERROR] plugin.yaml missing"; exit 1; fi
	@grep -q "base: core24" snap/snapcraft.yaml || (echo "[ERROR] base must be core24"; exit 1)
	@grep -q "bin/ct-engine run" snap/snapcraft.yaml || (echo "[ERROR] command must use ct-engine"; exit 1)
	@echo "[OK] Validation passed"

build:
	@echo "Building Snap Package"
	@echo "======================"
	@echo "-> Running $(SNAPCRAFT) $(SNAPCRAFT_FLAGS)..."
	@$(SNAPCRAFT) $(SNAPCRAFT_FLAGS)
	@mkdir -p dist
	@mv *.snap dist/
	@echo "[OK] Built: dist/$$(ls dist/ | grep .snap | tail -1)"

install:
	@echo "Installing Snap Locally"
	@echo "========================"
	@sudo snap install dist/*.snap --dangerous

logs:
	@snap logs -f $(SNAP_NAME)